version: '3'

services:
  nginx: # nginx v1.21
    image: nginx:1.21.6
    ports:
      - '8080:80'
    depends_on:
      - php
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  php: # PHP v8.0
    build: ./docker/php
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
  mysql: # MySQL 8.0
    platform: linux/x86_64
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
volumes:
  mysql-data:
